# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GettingStarted' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GettingStarted
  pod 'AppCenter/Crashes', '~> 1.0.1'
  pod 'AppCenter/Analytics', '~> 1.0.1'
  pod 'AppCenterReactNativeShared', '~> 1.0.1'

  

  target 'GettingStartedTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GettingStarted-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GettingStarted-tvOS

  target 'GettingStarted-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
